### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder

### ISSUE THREAD

**Issue by tiagohm** [tiagohm/EasyAdapter#1]
Está ocorrendo este erro:
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{5af6f30 position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{a544e5c VFED..... .F....I. 48,20-560,216 #7f0b0076 app:id/listaDeDispositivos}, adapter:br.tiagohm.easyadapter.EasyAdapter@ced9565, layout:android.support.v7.widget.LinearLayoutManager@5cb923a, context:com.tiagohm.bluedroid.app.MainActivity@f0e289d
                                                       at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5447)
                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5629)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3670)
                                                       at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3129)
                                                       at android.view.View.measure(View.java:18811)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                       at android.view.View.measure(View.java:18811)
                                                       at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1283)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                       at android.widget.ScrollView.onMeasure(ScrollView.java:340)
                                                       at android.view.View.measure(View.java:18811)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                       at android.view.View.measure(View.java:18811)
                                                       at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:295)
                                                       at android.view.View.measure(View.java:18811)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                       at android.view.View.measure(View.java:18811)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                       at android.view.View.measure(View.java:18811)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2645)
                                                       at android.view.View.measure(View.java:18811)
                                                       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2127)
                                                       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1243)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1479)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                       at android.os.Handler.handleCallback(Handler.java:742)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                   	at android.app.
```

**Comment by tiagohm** [comment]
Obrigado por avisar. Vou consertar isso agora mesmo.

**Comment by tiagohm** [comment]
O erro ainda persiste. Após a lista ser limpa e popular um item.
